# Generated by Django 3.2.9 on 2021-11-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recepient',
            field=models.EmailField(default='boy@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
