# Generated by Django 3.2.9 on 2021-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_email_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='anon',
            field=models.BooleanField(default=False),
        ),
    ]
