# Generated by Django 3.2.9 on 2021-11-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_email_anon'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.TextField(default='grey'),
            preserve_default=False,
        ),
    ]
